/**
 * Amharic translations for Dispatch
 */

import type { Messages } from "./en";

const am: Messages = {
  // ─── Brand ──────────────────────────────────────────────────────────────────
  brand: {
    name: "Dispatch",
    tagline: "የተዋሃደ የሎጂስቲክስ መድረክ",
    description:
      "ነጋዴዎችን ከኩሪየር አቅራቢዎች ጋር የሚያገናኝ ሶፍትዌር፣ የ shipment ፈጠራን፣ ኩሪየር ምርጫን፣ እና የዕቃ ክትትልን በአንድ ኃይለኛ መድረክ ያቃልላል።",
  },

  // ─── Navigation ─────────────────────────────────────────────────────────────
  nav: {
    features: "ባህሪያት",
    howItWorks: "እንዴት ይሰራል",
    portals: "መግቢያዎች",
    login: "ግባ",
    getStarted: "ጀምር",
  },

  // ─── Landing Hero ───────────────────────────────────────────────────────────
  hero: {
    badge: "ለአዲስ አበባ ሎጂስቲክስ የተሰራ",
    headline1: "ለእያንዳንዱ ዕቃ አቅርቦት",
    headline2: "ትክክለኛው አቋራጭ።",
    downloadDriverApp: "የሾፌር መተግበሪያ አውርድ",
    merchantLogin: "ነጋዴ ግባ",
    scroll: "ወደታች ሸብልል",
  },

  // ─── Stats ──────────────────────────────────────────────────────────────────
  stats: {
    courierPartners: "የኩሪየር አጋሮች",
    activeMerchants: "ንቁ ነጋዴዎች",
    deliveriesCompleted: "የተጠናቀቁ ዕቃ አቅርቦቶች",
    avgDeliveryTime: "አማካይ የማቅረቢያ ጊዜ",
  },

  // ─── Features Section ────────────────────────────────────────────────────────
  features: {
    sectionLabel: "መድረክ",
    headline1: "የሚያስፈልጉዎት ሁሉ።",
    headline2: "የማይሻሉትን ሳይጨምር።",
    shipmentManagement: {
      title: "የ Shipment አወዳደር",
      description:
        "ከብዙ የኩሪየር አቅራቢዎች በአንድ ወጥ ዳሽቦርድ shipmentዎችን ፍጠር፣ ክትተለ፣ እና አስተዳድር።",
    },
    fleetCoordination: {
      title: "የፍሊት ቅንጅት",
      description:
        "በቅጽበታዊ ሾፌር ክትትል፣ ብልጥ የመንገድ አወዳደር፣ እና የዕቃ አቅርቦት ማረጋገጫ ዓሠራሮች።",
    },
    performanceAnalytics: {
      title: "የአፈጻጸም ትንታኔ",
      description:
        "በይነተገናኝ ትንታኔ አማካይነት የኩሪየር አፈጻጸምን፣ የዕቃ አቅርቦት ጊዜን፣ እና የስኬት ደረጃዎችን አወዳድር።",
    },
    apiIntegration: {
      title: "የ API ውህደት",
      description:
        "ከ e-commerce መድረኮች ጋር ቀላል ውህደት ለማድረግ ቁልፍ አወዳደር ያለው RESTful API።",
    },
    locationIntelligence: {
      title: "የቦታ ብልህነት",
      description:
        "ለአዲስ አበባ ልዩ አድራሻ ስርዓት የተዘጋጀ የምልክት-ቦታ መፍቻ።",
    },
    courierRatings: {
      title: "የኩሪየር ደረጃ አሰጣጥ",
      description:
        "ከእውነተኛ የዕቃ አቅርቦት አፈጻጸም ውሂብ ተመስርቶ የኩሪየር አቅራቢዎችን ደምድም እና አወዳድር።",
    },
  },

  // ─── How It Works ───────────────────────────────────────────────────────────
  howItWorks: {
    sectionLabel: "ሂደት",
    headline: "በደቂቃዎች ጀምር።",
    step1: {
      title: "ተመዝገብ",
      description:
        "የነጋዴ ሂሳብህን በንግድ ዝርዝሮችህ ፍጠር እና ወዲያው የመድረኩን ተደራሽነት አግኝ።",
    },
    step2: {
      title: "ኩሪየር ምረጥ",
      description:
        "ያሉ ኩሪየሮችን ዳስስ፣ ዋጋዎችን፣ የአፈጻጸም መለኪያዎችን፣ እና የዕቃ አቅርቦት ቦታዎችን አወዳድር።",
    },
    step3: {
      title: "ላክ እና ክትተለ",
      description:
        "Shipmentዎችን ፍጠር፣ በቅጽበት ክትተለ፣ የማቅረቢያ ማረጋገጫ አግኝ፣ እና ሎጂስቲክስ ተንተን።",
    },
  },

  // ─── Portals Section ────────────────────────────────────────────────────────
  portals: {
    sectionLabel: "መግቢያዎች",
    headline: "ለእያንዳንዱ ሚና የተሰራ።",
    subheading:
      "በዕቃ አቅርቦት ሰንሰለት ውስጥ ላለ እያንዳንዱ ባለድርሻ አካል የተለዩ ዳሽቦርዶች።",
    merchant: {
      title: "ነጋዴ",
      description: "Shipmentዎችን ፍጠር፣ ኩሪየሮችን አወዳድር፣ እና ዕቃ አቅርቦቶችን ክትተለ።",
    },
    supervisor: {
      title: "የኩሪየር ሱፐርቫይዘር",
      description: "ሾፌሮችን አስተዳድር፣ Shipmentዎችን ምደብ፣ እና ፍሊቱን ክትተለ።",
    },
    admin: {
      title: "አስተዳዳሪ",
      description: "መድረኩን፣ ኩሪየሮችን፣ እና የሲስተም መለኪያዎችን ተቆጣጠር።",
    },
  },

  // ─── CTA Section ────────────────────────────────────────────────────────────
  cta: {
    headline1: "ሎጂስቲክስህን ለማቅለል",
    headline2: "ዝግጁ ነህ?",
    subheading:
      "Dispatchን ተቀላቀልና ዛሬ ንግዱን ከአዲስ አበባ ኩሪየር መረብ ጋር አገናኝ።",
    createAccount: "የነጋዴ ሂሳብ ፍጠር",
    courierLogin: "የኩሪየር ግቢያ",
  },

  // ─── Footer ─────────────────────────────────────────────────────────────────
  footer: {
    copyright: "© 2026 Dispatch. ለአዲስ አበባ የተሰራ።",
    merchant: "ነጋዴ",
    supervisor: "ሱፐርቫይዘር",
    downloadDriverApp: "የሾፌር መተግበሪያ አውርድ",
    admin: "አስተዳዳሪ",
  },

  // ─── Login Page ─────────────────────────────────────────────────────────────
  login: {
    welcomeBack: "እንኳን ደህና ተመለሱ",
    platformDescription:
      "ነጋዴዎችን እና የኩሪየር አቅራቢዎችን በአዲስ አበባ የሚያገናኝ የተዋሃደ የሎጂስቲክስ መድረክ።",
    back: "ተመለስ",
    emailLabel: "ኢሜይል",
    emailPlaceholder: "you@example.com",
    passwordLabel: "የሚስጥር ቁጥር",
    forgotPassword: "የሚስጥር ቁጥርዎን ረሱ?",
    signIn: "ግባ",
    signingIn: "በመግባት ላይ...",
    switchPortal: "ወደ ሌላ መግቢያ ቀይር",

    roles: {
      merchant: {
        label: "ነጋዴ",
        subtitle: "Shipmentዎችን ያስተዳድሩ እና ዕቃ አቅርቦቶችን ይከታተሉ",
      },
      supervisor: {
        label: "የኩሪየር ሱፐርቫይዘር",
        subtitle: "ሾፌሮችን እና የፍሊት ስራዎችን ያስተዳድሩ",
      },
      admin: {
        label: "አስተዳዳሪ",
        subtitle: "የመድረኩን ስራዎች እና መለኪያዎች ይቆጣጠሩ",
      },
    },

    validation: {
      emailRequired: "ኢሜይል ያስፈልጋል።",
      emailInvalid: "እባክዎ ትክክለኛ ኢሜይል አድራሻ ያስገቡ።",
      emailTooLong: "ኢሜይሉ ከ 255 ፊደሎች ያነሰ መሆን አለበት።",
      passwordRequired: "የሚስጥር ቁጥር ያስፈልጋል።",
      passwordTooShort: "የሚስጥር ቁጥሩ ቢያንስ 8 ቁምፊዎች ሊኖሩት ይገባል።",
    },

    lockout: {
      message: "ብዙ ስህተታ ሙከራዎች። እባክዎ በ {time} ውስጥ እንደገና ይሞክሩ።",
    },
  },

  // ─── Dashboard Stubs ────────────────────────────────────────────────────────
  dashboards: {
    merchant: {
      title: "የነጋዴ ዳሽቦርድ",
      welcome: "ወደ Dispatch የነጋዴ መግቢያ እንኳን ደህና ተመለሱ።",
    },
    supervisor: {
      title: "የኩሪየር ሱፐርቫይዘር ዳሽቦርድ",
      welcome: "ወደ Dispatch የሱፐርቫይዘር መግቢያ እንኳን ደህና ተመለሱ።",
    },
    admin: {
      title: "የአስተዳዳሪ ዳሽቦርድ",
      welcome: "ወደ Dispatch አስተዳደር መግቢያ እንኳን ደህና ተመለሱ።",
    },
    returnToWebsite: "ወደ ድህረ-ገጹ ተመለስ",
    logout: "ውጣ",
  },

  // ─── Supervisor Profile ──────────────────────────────────────────────────────
  profile: {
    title: "የኩሪየር መረጃ",
    subtitle: "የኩሪየር ምስል መረጃዎችን ይመልከቱ",
    companyInfo: "የምስል መረጃ",
    contactInfo: "የመገናኛ መረጃ",
    companyName: "የምስል ስም",
    companyAddress: "አድራሻ",
    supportPhone: "የድጋፍ ስልክ",
    email: "ኢሜይል",
    website: "ድህረ-ገጽ",
    status: "ሁኔታ",
    operationalZones: "የስራ አካባቢዎች",
    operationalZonesDesc: "የስራ አካባቢዎች በአስተዳዳሪ ይውተራሹ።",
    ratingPricing: "ደረጃ እና ዋጋ",
    rating: "ደረጃ",
    reviews: "ግምገማዎች",
    maxWeight: "ከፍተኛ ክወና",
    basePrice: "መሰረታዊ ዋጋ",
    rateDetails: "የደረጃ ዝርዝሮች",
    weightRate: "የክወና ዋጋ",
    distanceRate: "የርቀት ዋጋ",
    timeRate: "የጊዜ ዋጋ",
    viewProfile: "የምስል መረጃ ይመልከቱ",
    errorLoading: "ፕሮፋይሉን መጫን አልተቻለም",
    noProfileData: "ምንም የፕሮፋይል መረጃ የለም",
    noProfileDataDesc: "የፕሮፋይል መረጃ የለም። እባክዎ አስተዳዳሪውን ያነጋግሩ።",
    returnToDashboard: "ወደ ዳሽቦርድ ይመለሱ",
    tryAgain: "እንደገና ይሞክሩ",
    editBtn: "አስተካክል",
    perKg: "በኪሎ ግራም",
    perKm: "በኪሎ ሜትር",
    perMin: "በደቂቃ",
    incomplete: {
      title: "ያልተሟላ ፕሮፋይል",
      description: "የኩባንያዎን መረጃ ለማሟላት አስተዳዳሪውን ያነጋግሩ።",
    },
    editDialog: {
      title: "የኩባንያ መገለጫ አርትዕ",
      logo: "የኩባንያ አርማ",
      changeLogo: "አርማ ቀይር",
      uploadLogo: "አርማ ስቀል",
      remove: "አስወግድ",
      logoTip: "JPG, PNG ወይም WEBP. ቢበዛ 5MB።",
      companyName: "የኩባንያ ስም *",
      address: "አድራሻ *",
      phone: "ስልክ ቁጥር *",
      email: "ኢሜይል",
      website: "የድረ-ገጽ አድራሻ (URL)",
      pricingSection: "የዋጋ አወሳሰን እና አቅም",
      maxWeight: "ከፍተኛ ክብደት (kg)",
      basePrice: "መሰረታዊ ዋጋ (ETB)",
      weightRate: "የክብደት ተመን (ETB/kg)",
      distanceRate: "የእርቀት ተመን (ETB/km)",
      timeRate: "የጊዜ ተመን (ETB/min)",
      cancel: "ተው",
      submit: "ለውጦችን አስቀምጥ",
      success: "የኩባንያው መረጃ በተሳካ ሁኔታ ተዘምኗል።",
      errors: {
        companyNameRequired: "የኩባንያ ስም ያስፈልጋል",
        addressRequired: "አድራሻ ያስፈልጋል",
        maxWeightExceeded: "ከፍተኛ ክብደት ከ10,000 ኪ.ግ መብለጥ የለበትም",
        basePriceExceeded: "መሰረታዊ ዋጋ ከ100,000 ብር መብለጥ የለበትም",
        weightRateExceeded: "የክብደት ተመን ከ10,000 ብር/ኪ.ግ መብለጥ የለበትም",
        distanceRateExceeded: "የእርቀት ተመን ከ10,000 ብር/ኪ.ሜ መብለጥ የለበትም",
        timeRateExceeded: "የጊዜ ተመን ከ10,000 ብር/ደቂቃ መብለጥ የለበትም",
      },
    },
  },

  // ─── Supervisor Dashboard ───────────────────────────────────────────────────
  supervisorDashboard: {
    pendingAssignments: "በሂደት ላይ ያሉ ትዕዛዞች",
    inTransit: "በመንገድ ላይ",
    completedToday: "ዛሬ የተጠናቀቁ",
    revenueToday: "የዛሬ ገቢ",
    driverStatus: "የሾፌሮች ሁኔታ",
    viewAll: "ሁሉንም ይመልከቱ",
    deliveryRate: "የዕቃ አቅርቦት ፍጥነት",
    driverUtilization: "የሾፌሮች አጠቃቀም",
    rating: "ደረጃ",
    assign: "ምደብ",
    merchants: "ነጋዴዎች",
    destination: "መድረሻ",
    id: "መለያ",
    actions: "ድርጊቶች",
    inProgress: "በሂደት ላይ",
    success: "ስኬት",
    last7Days: "ያለፉት 7 ቀናት",
    totalShipments: "ጠቅላላ ትዕዛዞች",
    assignShipment: "ትዕዛዝ ምደብ",
    overview: "የፍሊት አጠቃላይ እይታ",
    performanceStatus: "የአፈጻጸም መለኪያዎች",
    performanceTitle: "የዛሬው የአፈጻጸም ሁኔታ",
    fleetManagement: "የፍሊት አስተዳደር",
    deliveriesToday: "የዛሬ አቅርቦቶች",
    welcomeBack: "እንኳን ደህና መጡ፣ {name}",
    todaysOperations: "የዛሬው የቀን ክንውኖች",
    refresh: "አድስ",
    viewShipments: "ትዕዛዞችን ይመልከቱ",
    attentionNeeded: "ትኩረት ያስፈልጋል",
    awaitingAssignment: "{count} ትዕዛዞች ሾፌር በመጠባበቅ ላይ {s}",
    pendingCount: "{count} በሂደት ላይ ያሉ ትዕዛዞች {s}",
    review: "ግምገማ",
    awaitingAssignmentSub: "ምደባ በመጠባበቅ ላይ",
    onTheRoad: "በመንገድ ላይ",
    failedToday: "{count} ዛሬ ያልተሳኩ",
    noFailuresToday: "ዛሬ ምንም የከሸፈ የለም",
    fromCompletedDeliveries: "ከተጠናቀቁ አቅርቦቶች",
    actionItems: "ትኩረት የሚሹ ጉዳዮች",
    viewAllShipments: "ሁሉንም ትዕዛዞች ይመልከቱ →",
    allCaughtUp: "ሁሉም ተጠናቅቋል",
    noPendingUnassigned: "ምንም በመጠባበቅ ላይ ወይም ያልተመደበ ትዕዛዝ የለም",
    noDescription: "መግለጫ የለም",
    fleetStatus: "የፍሊት ሁኔታ",
    detailsLink: "ዝርዝር →",
    activeLabel: "ንቁ",
    inFleet: "በፍሊት ውስጥ",
    onDeliveryLabel: "በስራ ላይ",
    utilizationLabel: "{rate}% አጠቃቀም",
    idleAvailableLabel: "ዝግጁ / ስራ ላይ ያልሆኑ",
    readyForAssignments: "ለስራ ዝግጁ",
    manageDrivers: "ሾፌሮችን ያስተዳድሩ",
    queueManagement: "የሰልፍ ማስተዳደሪያ",
    allClear: "ሁሉም ሰላም ነው!",
    noPendingAssignments: "በአሁኑ ጊዜ በመጠባበቂያ ሰልፍ ውስጥ ምንም ትዕዛዝ የለም።",
  },
  sidebar: {
    dashboard: "ዳሽቦርድ",
    shipments: "ትዕዛዞች",
    drivers: "ሾፌሮች",
    fleet: "ፍሊት",
    revenue: "ገቢ",
    reports: "ሪፖርቶች",
    supervisors: "ሱፐርቫይዘሮች",
    settings: "መቼቶች",
    logOut: "ውጣ",
    roleTitle: "የኩሪየር ሱፐርቫይዘር",
    language: "ቋንቋ",
    theme: "ገጽታ",
    themes: {
      light: "ብርሃን",
      dark: "ጨለማ",
      system: "የስርዓቱ",
    },
  },

  supervisors: {
    title: "ሱፐርቫይዘሮች",
    subtitle: "የኩሪየር ኩባንያ ሱፐርቫይዘሮችን ያስተዳድሩ",
    addSupervisor: "ሱፐርቫይዘር ጨምር",
    ownerBadge: "ባለቤት",
    youBadge: "እርስዎ",
    loading: "ሱፐርቫይዘሮችን በመጫን ላይ...",
    retry: "እንደገና ሞክር",
    cancel: "ተው",
    close: "ዝጋ",
    editAction: "አርትዕ",
    deleteAction: "ሰርዝ",
    table: {
      name: "ስም",
      email: "ኢሜይል",
      phone: "ስልክ",
      status: "ሁኔታ",
      actions: "ድርጊቶች",
    },
    status: {
      active: "ንቁ",
      inactive: "ንቁ ያልሆነ",
      pending: "በመጠባበቅ ላይ",
    },
    create: {
      title: "ሱፐርቫይዘር ጨምር",
      description: "ለኩሪየር ኩባንያዎ አዲስ ሱፐርቫይዘር ይፍጠሩ።",
      firstName: "የመጀመሪያ ስም",
      middleName: "የአባት ስም",
      lastName: "የቤተሰብ ስም",
      email: "ኢሜይል",
      phone: "ስልክ ቁጥር",
      password: "የሚስጥር ቁጥር",
      generating: "እየፈጠረ...",
      regenerate: "እንደገና ፍጠር",
      firstNamePlaceholder: "ዮሃንስ",
      middleNamePlaceholder: "አማራጭ",
      lastNamePlaceholder: "ተስፋዬ",
      emailPlaceholder: "yohannes@example.com",
      phonePlaceholder: "+251911234567",
      submit: "ሱፐርቫይዘር ፍጠር",
      submitting: "እየተፈጠረ...",
      success: "ሱፐርቫይዘር በተሳካ ሁኔታ ተፈጥሯል።",
    },
    edit: {
      title: "ሱፐርቫይዘር አርትዕ",
      description: "የሱፐርቫይዘር መረጃ ያዘምኑ።",
      firstName: "የመጀመሪያ ስም",
      middleName: "የአባት ስም",
      lastName: "የቤተሰብ ስም",
      email: "ኢሜይል",
      phone: "ስልክ ቁጥር",
      status: "ሁኔታ",
      submit: "ለውጦችን አስቀምጥ",
      submitting: "እየተቀመጠ...",
      success: "ሱፐርቫይዘር በተሳካ ሁኔታ ተዘምኗል።",
    },
    delete: {
      title: "ሱፐርቫይዘር ሰርዝ",
      description: "ይህ የሱፐርቫይዘር መለያን በቋሚነት ያስወግዳል። ይህ ድርጊት መቀልበስ አይቻልም።",
      confirm: "ይህ መቀልበስ እንደማይቻል ተረድቻለሁ",
      submit: "ሱፐርቫይዘር ሰርዝ",
      submitting: "እየተሰረዘ...",
      success: "ሱፐርቫይዘር በተሳካ ሁኔታ ተሰርዟል።",
    },
    empty: "ምንም ሱፐርቫይዘሮች አልተገኙም።",
    errorLoad: "ሱፐርቫይዘሮችን መጫን አልተሳካም።",
  },

  // ─── Shipments Management ───────────────────────────────────────────────────
  shipments: {
    title: "ትዕዛዞች",
    subtitle: "ትዕዛዞችን ያስተዳድሩ እና ለሾፌሮች ይመድቡ",
    searchPlaceholder: "ትዕዛዞችን ይፈልጉ...",
    filters: {
      all: "ሁሉም",
      pending: "በሂደት ላይ",
      assigned: "ተመድቧል",
      inTransit: "በመንገድ ላይ",
      delivered: "የደረሱ",
      failed: "ያልተሳካ",
      cancelled: "የተሰረዘ",
      allDrivers: "ሁሉም ሾፌሮች",
      unassigned: "ያልተመደበ",
      advanced: "ተጨማሪ ማጣሪያዎች",
      narrowDown: "ትዕዛዞችን በዝርዝር ይለዩ",
      dateRange: "የቀን ገደብ",
      to: "እስከ",
      driverAssignment: "የሾፌር ምደባ",
      clearAdvanced: "ተጨማሪ ማጣሪያዎችን አጽዳ",
      resetAll: "ሁሉንም አጽዳ",
      fromLabel: "ከ:",
      toLabel: "ለ:",
      driverLabel: "ሾፌር:",
      dateError: "የመጀመሪያው ቀን ከሁለተኛው ቀን መቅደም አለበት",
    },
    table: {
      id: "መለያ",
      merchant: "ነጋዴ",
      recipient: "ተቀባይ",
      pickup: "መረከቢያ",
      delivery: "ማድረሻ",
      route: "መንገድ",
      driver: "ሾፌር",
      status: "ሁኔታ",
      fee: "ክፍያ",
      actions: "ድርጊቶች",
      created: "የተፈጠረበት",
    },
    status: {
      pending: "በመጠባበቅ ላይ",
      assigned: "የተመደበ",
      assigned_to_courier: "ለኩሪየር ተመድቧል",
      assigned_to_driver: "ለሾፌር ተመድቧል",
      picked_up: "ተወስዷል",
      in_transit: "በመንገድ ላይ",
      out_for_delivery: "ለማድረስ የወጣ",
      delivered: "የደረሰ",
      failed: "ያልተሳካ",
      returned: "የተመለሰ",
      cancelled: "የተሰረዘ",
      urgent: "አስቸኳይ",
      unassigned: "ያልተመደበ",
    },
    empty: {
      title: "ምንም ትዕዛዝ አልተገኘም",
      description: "እባክዎን ማጣሪያዎችን ወይም የፍለጋ ቃላትን ያስተካክሉ።",
      noAssignments: "ለእርስዎ ኩባንያ እስካሁን የተመደበ ትዕዛዝ የለም።",
    },
    errorLoad: "ትዕዛዞችን መጫን አልተቻለም",
    retry: "እንደገና ይሞክሩ",
    selectAll: "ሁሉንም ምረጥ",
    batchAssign: "በቡድን ምደብ",
    selected: "ተመርጠዋል",
    clear: "አጽዳ",
    assignDriver: "ሾፌር ምደብ",
    viewDetails: "ዝርዝር ይመልከቱ",
    rowsPerPage: "በአንድ ገጽ",
    pageOf: "ገጽ {page} ከ {total}",
    totalCount: "{count} ትዕዛዞች",
    details: {
      title: "የትዕዛዝ ዝርዝር",
      notFound: "ትዕዛዙ አልተገኘም",
      accessDenied: "የመግባት ፈቃድ የለዎትም",
      failedLoad: "ትዕዛዙን መጫን አልተቻለም",
      backToShipments: "ወደ ትዕዛዞች ዝርዝር ተመለስ",
      basicInfo: "መሰረታዊ መረጃ",
      trackingNumber: "የክትትል ቁጥር",
      merchant: "ነጋዴ",
      created: "የተመዘገበበት",
      statusHistory: "የሁኔታ ታሪክ",
      assignedDriver: "የተመደበ ሾፌር",
      noDriver: "የተመደበ ሾፌር የለም",
      name: "ስም",
      phone: "ስልክ",
      email: "ኢሜይል",
      pickupAddress: "የመነሻ አድራሻ",
      deliveryAddress: "የመድረሻ አድራሻ",
      contact: "ተጠሪ:",
      packageDetails: "የዕቃው ዝርዝር",
      weight: "ክብደት",
      dimensions: "ልክ (Dimensions)",
      deliveryFee: "የማቅረቢያ ክፍያ",
      items: "ዕቃዎች",
      itemsCount: "{count} ዕቃ(ዎች)",
      itemList: "የዕቃዎች ዝርዝር",
      notes: "ማስታወሻዎች",
      mapExpand: "አስፋ",
      mapClose: "ዝጋ",
      mapPickup: "መነሻ",
      mapDelivery: "መድረሻ",
    },
    timeline: {
      created: "ተመዝግቧል",
      assigned_to_courier: "ለድርጅት ተመድቧል",
      assigned_to_driver: "ለሾፌር ተመድቧል",
      picked_up: "ተረክቧል",
      in_transit: "በመንገድ ላይ",
      delivered: "ደረሰ",
      failed: "አልተሳካም",
      returned: "ተመለሰ",
      cancelled: "ተሰረዘ",
    },
    assignDialog: {
      title: "ሾፌር መድብ",
      description: "ለጭነት {code} ሾፌር መድብ",
      cannotAssign: "ቀድሞውኑ {status} ለሆነ ጭነት ሾፌር መመደብ አይቻልም።",
      alreadyAssigned: "ይህ ጭነት ቀድሞውኑ ለ{name} ተመድቧል። አዲስ ሾፌር መመደብ ቀድሞ የተመደበውን ይቀይረዋል።",
      driverAlreadyAssigned: "ይህ ጭነት ቀድሞውኑ ለሾፌር ተመድቧል። ለሌላ ሾፌር ለመምደብ ኩሪየሩ አሁን ያለውን ሾፌር ማስወጣት አለበት።",
      summary: {
        description: "መግለጫ፦",
        route: "መንገድ፦",
        fee: "ክፍያ፦",
      },
      selectDriverLabel: "Select Driver",
      loadingDrivers: "ሾፌሮች በመጫን ላይ...",
      noActiveDrivers: "ምንም ንቁ ሾፌሮች የሉም። መጀመሪያ ሾፌር ይፍጠሩ።",
      chooseDriverPlaceholder: "ሾፌር ይምረጡ...",
      assignedSuccess: "ለ{name} በ{time} ተመድቧል",
      submit: "ሾፌር መድብ",
    },
    batchAssignDialog: {
      title: "በጅምላ ሾፌር መድብ",
      description: "{count} ጭነቶችን ለአንድ ሾፌር መድብ",
      selectedShipments: "የተመረጡ ጭነቶች",
      loadingDrivers: "ሾፌሮች በመጫን ላይ...",
      noActiveDrivers: "ምንም ንቁ ሾፌሮች የሉም።",
      selectDriverLabel: "Select Driver",
      chooseDriverPlaceholder: "ሾፌር ይምረጡ...",
      successMsg: "{count} ጭነቶች ለ{name} ተመድበዋል",
      failedMsg: "{count} አልተሳካም",
      close: "ዝጋ",
      cancel: "ተው",
      submit: "{count} ጭነቶችን መድብ",
    },
  },

  // ─── Driver Management ──────────────────────────────────────────────────────
  drivers: {
    title: "ሾፌሮች",
    subtitle: "የዕቃ አቅራቢ ሾፌሮችን ያስተዳድሩ",
    manageFleet: "የሾፌር ፍሊትዎን ያስተዳድሩ",
    searchPlaceholder: "ሾፌሮችን ይፈልጉ...",
    addDriver: "ሾፌር ጨምር",
    phone: "ስልክ",
    email: "ኢሜይል",
    filters: {
      all: "ሁሉም",
      active: "ንቁ",
      inactive: "ያልነቁ",
      pending: "በሂደት ላይ",
    },
    table: {
      driver: "ሾፌር",
      vehicle: "ተሽከርካሪ",
      deliveries: "አቅርቦቶች",
      status: "ሁኔታ",
      rating: "ደረጃ",
      actions: "ድርጊቶች",
      phone: "ስልክ",
      email: "ኢሜይል",
    },
    status: {
      active: "ንቁ",
      inactive: "ያልነቁ",
      onBreak: "በእረፍት ላይ",
      busy: "ሥራ ላይ",
      pending: "በመጠባበቅ ላይ",
    },
    empty: {
      title: "ምንም ሾፌር አልተገኘም",
      description: "እባክዎን የፍለጋ ቃላትን ወይም የማጣሪያ ሁኔታን ያረጋግጡ።",
      noDriversInFleet: "በፍሊትዎ ውስጥ እስካሁን ምንም ሾፌር የለም።",
    },
    addFirstDriver: "የመጀመሪያውን ሾፌር ጨምር",
    errorLoad: "ሾፌሮችን መጫን አልተቻለም",
    retry: "እንደገና ይሞክሩ",
    selectAllDrivers: "ሁሉንም ሾፌሮች ምረጥ",
    editDriver: "ሾፌር አድስ",
    viewPerformance: "አፈጻጸምን ይመልከቱ",
    deactivate: "አሰናብት",
    activate: "አግብር",
    delete: "ሰርዝ",
    compare: "አወዳድር",
    selected: "ተመርጠዋል",
    dialogs: {
      cancel: "ተው",
      done: "አጠናቅቅ",
      create: {
        title: "አዲስ ሾፌር ጨምር",
        description: "ለኩሪየር ኩባንያዎ የሾፌር መለያ ይፍጠሩ",
        success: "ሾፌር በተሳካ ሁኔታ ተፈጥሯል",
        driverId: "የሾፌር መለያ (ID)፦ #{id}",
        credentials: "የመግቢያ መረጃ",
        saveCredentialsNote: "ይህንን የመግቢያ መረጃ ያስቀምጡ — የይለፍ ቃሉን በኋላ ላይ ማግኘት አይቻልም።",
        firstName: "የመጀመሪያ ስም *",
        middleName: "የአባት ስም",
        lastName: "የቤተሰብ ስም *",
        email: "ኢሜይል *",
        phone: "ስልክ ቁጥር *",
        vehicleType: "የተሽከርካሪ ዓይነት *",
        selectType: "ዓይነት ይምረጡ...",
        vehicleTypes: {
          motorcycle: "ሞተርሳይክል",
          bicycle: "ብስክሌት",
          car: "መኪና",
          van: "ቫን",
          truck: "ጭነት መኪና",
          other: "ሌላ",
        },
        licensePlate: "ሰሌዳ ቁጥር *",
        emergencyContact: "የአደጋ ጊዜ ተጠሪ *",
        passwordLabel: "የይለፍ ቃል *",
        autoGenerate: "በራስ-ሰር ፍጠር",
        setCustom: "በራስዎ ይለፍ ቃል ያዘጋጁ",
        regenerate: "እንደገና ፍጠር",
        enterPassword: "የይለፍ ቃል ያስገቡ",
        confirmPassword: "የይለፍ ቃል ያረጋግጡ",
        passwordRule: "ቢያንስ 8 ፊደላት፣ ካፒታልና ስሞል ፊደላት፣ ቁጥር እና ልዩ ምልክቶችን ማካተት አለበት",
        submit: "ሾፌር ፍጠር",
      },
      edit: {
        title: "ሾፌር አርትዕ",
        description: "ለ{name} መለያ መረጃውን ያዘምኑ",
        success: "ሾፌር በተሳካ ሁኔታ ተዘምኗል",
        changedFields: "የተቀየረ፦ {fields}",
        profilePhoto: "የመገለጫ ምስል",
        changePhoto: "ምስል ቀይር",
        uploadPhoto: "ምስል ስቀል",
        submit: "ለውጦችን አስቀምጥ",
      },
      delete: {
        title: "ሾፌር ሰርዝ",
        description: "የ{name} መለያን በቋሚነት ያስወግዱ",
        success: "ሾፌር ተሰርዟል",
        successDesc: "የ{name} መለያ ተሰርዟል። ያለፉ የትዕዛዝ መዝገቦች ተጠብቀው ይቆያሉ።",
        submit: "በቋሚነት ሰርዝ",
        cannotDeleteTitle: "መሰረዝ አይቻልም — {count} ትዕዛዝ(ቶች) በሂደት ላይ ናቸው",
        cannotDeleteDesc: "ይህን ሾፌር ከመሰረዝዎ በፊት በሂደት ላይ ያሉትን ሁሉንም ትዕዛዞች እንደገና ይመድቡ ወይም ያጠናቅቁ።",
        permanentWarning: "ይህ ድርጊት ቋሚ ነው እናም፦",
        permList: {
          login: "የ{name} መግቢያ መለያን ያስወግዳል",
          lists: "ከሁሉም የሾፌሮች ዝርዝር ውስጥ ያስወግዳቸዋል",
          audit: "ለኦዲት ሲባል ያለፉ የትዕዛዝ መዝገቦችን ይጠብቃል",
        },
        checkboxLabel: "ይህ ድርጊት ቋሚ እንደሆነ እና መቀልበስ እንደማይቻል ተረድቻለሁ",
      },
      deactivate: {
        title: "ሾፌር አግድ",
        description: "ለጊዜው የ{name} መለያን ያግዱ",
        success: "ሾፌር ታግዷል",
        successDesc: "{name} ከእንግዲህ አዲስ ስራዎችን መቀበል ወይም መግባት አይችልም።",
        submit: "አግድ",
        activeAssignments: "{count} ንቁ ስራ(ዎች)",
        activeAssignmentsDesc: "ይህ ሾፌር በሂደት ላይ ያሉ ስራዎች አሉት። ከመታገዱ በፊት እንደገና መመደብን ያስቡበት።",
        warningTitle: "ይህን ሾፌር ማገድ፦",
        warningList: {
          login: "ወደ ሞባይል መተግበሪያ እንዳይገቡ ይከላከላል",
          newAssignments: "ከአዲስ ስራዎች ምደባ ዝርዝር ውስጥ ያስወጣቸዋል",
          preserve: "ሁሉንም ያለፉ መረጃዎችን እና ስራዎችን ይጠብቃል",
        },
      },
      reactivate: {
        title: "ሾፌር መልሰህ አንቃ",
        description: "የ{name} መለያን ወደ ንቁ ሁኔታ ይመልሱ",
        success: "ሾፌር መልሶ ነቅቷል",
        successDesc: "{name} አሁን ስራዎችን መቀበል እና መግባት ይችላል።",
        submit: "መልሰህ አንቃ",
        body: "ይህ የ{name} መለያን መልሶ ያንቀሳቅሳል። መግባት እና አዲስ የትዕዛዝ ስራዎችን መቀበል ይችላሉ።",
      },
    },
  },

  // ─── Revenue Management ─────────────────────────────────────────────────────
  revenue: {
    title: "ገቢ",
    subtitle: "ከደረሱ ትዕዛዞች የተገኘ ገቢ፣ ካለፈው ጊዜ ጋር በማነጻጸር",
    export: "አውርድ",
    pdfReport: "የPDF ሪፖርት",
    pdfDesc: "የተቀረጸ ሰነድ",
    excelReport: "የExcel ሰነድ",
    excelDesc: "ሊስተካከል የሚችል ሰነድ",
    empty: {
      title: "ምንም የገቢ መረጃ የለም",
      description: "ገቢ የሚሰላው በደረሱ ትዕዛዞች ነው። እባክዎን ሰፊ የቀን ገደብ ይሞክሩ።",
    },
    stats: {
      totalRevenue: "ጠቅላላ ገቢ",
      deliveries: "አቅርቦቶች",
      avgPerDelivery: "አማካይ በአንድ አቅርቦት",
      priorComparison: "ከ {amount} የቀድሞ ጋር ሲነጻጸር",
      avgNote: "በሁሉም የደረሱ ትዕዛዞች",
    },
    trend: {
      title: "የገቢ አዝማሚያ",
      subtitle: "በተመረጠው ጊዜ ውስጥ ያለው የቀን ገቢ",
    },
    topDrivers: {
      title: "ከፍተኛ ገቢ ያስገኙ ሾፌሮች",
      contributed: "{count} {s} ተሳትፈዋል",
      driver: "ሾፌር",
      drivers: "ሾፌሮች",
      deliveries: "{count} {s}",
      delivery: "አቅርቦት",
      deliveriesPlural: "አቅርቦቶች",
      share: "{pct}% ድርሻ",
    },
    presets: {
      d7: "7ቀ",
      d30: "30ቀ",
      d90: "90ቀ",
      custom: "ተጨማሪ",
    },
    calendar: {
      clear: "አጽዳ",
      apply: "ተግብር",
    },
  },
  driverPerformance: {
    notFound: "ሾፌሩ አልተገኘም",
    backToDrivers: "ወደ ሾፌሮች ተመለስ",
    statusActive: "ንቁ",
    export: "አውርድ",
    presets: {
      d7: "7 ቀን",
      d30: "30 ቀን",
      d90: "90 ቀን",
      custom: "ተለዋጭ",
    },
    picker: {
      pickStart: "የመጀመሪያ ቀን ይምረጡ",
      pickEnd: "የመጨረሻ ቀን ይምረጡ",
      clear: "አጽዳ",
      apply: "ተግብር",
    },
    reports: {
      pdf: "የPDF ሪፖርት",
      pdfDesc: "የተቀረጸ ሰነድ",
      excel: "የExcel ሰነድ",
      excelDesc: "ሊስተካከል የሚችል ሰነድ",
    },
    empty: {
      title: "ምንም የአቅርቦት መረጃ የለም",
      description: "በተመረጠው ጊዜ ውስጥ ለ {name} ምንም ትዕዛዝ አልተሰጠም።",
    },
    metrics: {
      delivered: "የደረሱ",
      total: "ከ {count} ጠቅላላ",
      successRate: "የስኬት መጠን",
      attempts: "{count} ሙከራዎች",
      failed: "ያልተሳኩ",
      rate: "{count}% መጠን",
      avgTime: "አማካይ ጊዜ",
      pickupToDelivery: "ጭነት → ማድረስ",
      dailyAvg: "የቀን አማካይ",
      deliveriesPerDay: "አቅርቦቶች / ቀን",
      avgRating: "አማካይ ደረጃ",
      ratingsCount: "{count} ደረጃዎች",
      noRatings: "ምንም ደረጃ የለም",
    },
    charts: {
      activity: "የማድረስ እንቅስቃሴ",
      breakdown: "የሁኔታ ዝርዝር",
      total: "ጠቅላላ",
    },
    failureReasons: {
      title: "ያልተሳኩባቸው ምክንያቶች",
      failedCount: "{count} ያልተሳኩ ትዕዛዞች",
    },
    calendar: {
      custom: "ተጨማሪ",
      pickStartDate: "የመጀመሪያ ቀን ይምረጡ",
      pickEndDate: "የመጨረሻ ቀን ይምረጡ",
      clear: "አጽዳ",
      apply: "ተግብር",
    },
  },
  driverCompare: {
    title: "ሾፌሮችን ያነጻጽሩ",
    subtitle: "ለ {count} ሾፌሮች ጎን ለጎን የተገመገመ አፈጻጸም",
    metrics: "የአፈጻጸም መለኪያዎች",
    top: "ከፍተኛ",
    bottom: "ዝቅተኛ",
    metricCol: "መለኪያ",
    loading: "የሁሉንም ሾፌሮች ጭነት መረጃ በመጫን ላይ...",
    empty: {
      title: "ቢያንስ 2 ሾፌሮችን ይምረጡ",
      description: "አፈጻጸማቸውን ለማነጻጸር ከሾፌሮች ዝርዝር ውስጥ ሁለት ወይም ከዚያ በላይ ሾፌሮችን ይምረጡ።",
      notFoundTitle: "ሾፌሮቹ አልተገኙም",
      notFoundDescription: "አንዳንድ የተመረጡ ሾፌሮችን መጫን አልተቻለም። እባክዎ ከሾፌሮች ዝርዝር ውስጥ እንደገና ይሞክሩ።",
    },
    backToDrivers: "ወደ ሾፌሮች ተመለስ",
    calendar: {
      custom: "ተጨማሪ",
    },
  },
  fleet: {
    title: "የተሽከርካሪዎች አገልግሎት",
    subtitle: "አቅም፣ የሥራ ስርጭት እና የአሰራር ግንዛቤዎች",
    presets: {
      today: "ዛሬ",
      week: "በዚህ ሳምንት",
      month: "በዚህ ወር",
      custom: "ተጨማሪ",
    },
    empty: {
      title: "በfleetዎ ውስጥ ምንም ገባሪ ሾፌሮች የሉም።",
      description: "የfleet አጠቃቀምን መከታተል ለመጀመር ከሾፌሮች ገጽ ሾፌሮችን ይጨምሩ።",
    },
    stats: {
      activeDrivers: "ንቁ ሾፌሮች",
      onDelivery: "በትዕዛዝ ላይ",
      idleDrivers: "ስራ የሌላቸው ሾፌሮች",
      shipments: "ትዕዛዞች",
      inFleet: "በቡድኑ ውስጥ",
      fleetPct: "{pct}% ከጠቅላላው",
      availableNow: "አሁን ይገኛሉ",
      deliveredCount: "{count} ደርሷል",
    },
    workload: {
      title: "የሥራ ስርጭት",
      summary: "{count} ሾፌሮች • አማካይ {avg} ትዕዛዞች/ሾፌር",
      delivered: "የደረሱ",
      inProgress: "በሂደት ላይ",
      failed: "ያልተሳኩ",
      scroll: "ሁሉንም {count} ሾፌሮች ለማየት ወደ ታች ይውረዱ",
    },
    peakHours: {
      title: "ከፍተኛ የሥራ ሰዓታት",
      subtitle: "በሰዓት ያለው እንቅስቃሴ",
      peak: "ከፍተኛ: {time}",
    },
    recommendations: {
      title: "የውሳኔ ሃሳቦች",
      subtitle: "ከአሁኑ የሥራ ጫና እና እንቅስቃሴ የተገኙ ግንዛቤዎች",
      balanced: "ቡድኑ የተመጣጠነ ነው። ለዚህ ጊዜ ምንም የአቅም ክፍተቶች ወይም የሥራ አለመመጣጠን አልተገኘም።",
      atCapacity: {
        title: "የሾፌሮች ቡድን በመጠባበቅ ላይ ነው",
        body: "{pct}% ንቁ ሾፌሮች በትዕዛዝ ላይ ናቸው። አዳዲስ ጥያቄዎችን ለማስተናገድ ተጨማሪ ሾፌሮችን ማሰማራት ወይም ዝቅተኛ ቅድሚያ የሚሰጣቸውን ስራዎች ማቆም ያስቡበት።",
      },
      tightening: {
        title: "የአቅም መቀነስ",
        body: "{pct}% የሾፌሮች ቡድን ተይዟል። ስራ የሌላቸው {count} {s} ብቻ ስለሆኑ ጥንቃቄ ያድርጉ።",
        driver: "ሾፌር",
        drivers: "ሾፌሮች",
      },
      spare: {
        title: "ትርፍ አቅም አለ",
        body: "ከ {total} ሾፌሮች መካከል {idle} ስራ የላቸውም። ቡድኑ ሳይመጣጠን አዳዲስ ትዕዛዞችን ማስተናገድ ይችላል።",
      },
      activation: {
        title: "ምርጥ የስራ ሰዓታት",
        body: "ፍላጎት በ {hours} ላይ ይጨምራል። መዘግየትን ለማስወገድ በእነዚህ ሰዓታት ተጨማሪ ሾፌሮችን ያዘጋጁ።",
      },
      overworked: {
        title: "ከመጠን በላይ የሰሩ",
        desc: "ከአማካይ 1.5 እጥፍ በላይ — አዳዲስ ትዕዛዞችን ለሌሎች ይስጡ",
      },
      underutilized: {
        title: "ዝቅተኛ ስራ የሰሩ",
        desc: "ከአማካይ 0.5 እጥፍ በታች — ተጨማሪ ትዕዛዞችን ይስጡ",
      },
    },
  },

  // ─── Fleet Map ──────────────────────────────────────────────────────────────
  fleetMap: {
    title: "የፍሊት ካርታ",
    subtitle: "የሾፌሮችዎን መልክዓ ምድራዊ ስርጭት በቅጽበት ይከታተሉ",
    sidebar: {
      activeDrivers: "ንቁ ሾፌሮች",
      idleDrivers: "ሥራ ያልያዙ / ዝግጁ",
      onDelivery: "በሥራ ላይ",
      searchPlaceholder: "ሾፌር ይፈልጉ...",
    },
    marker: {
      assignment: "ተግባር",
      status: "ሁኔታ",
      idle: "ዝግጁ",
      viewDetails: "ዝርዝር ይመልከቱ",
    },
  },

  settings: {
    title: "ቅንጅቶች",
    subtitle: "በሱፐርቫይዘር መግቢያ ላይ ያለዎትን ልምድ ያብጁ",
    language: {
      title: "ቋንቋ",
      description: "ለሜኑዎች፣ ለጽሁፎች እና ለመልእክቶች የሚሆን ቋንቋ ይምረጡ። ምርጫዎ በዚህ መሣሪያ ላይ ይቀመጣል።",
    },
    comingSoon: {
      title: "ተጨማሪ ቅንጅቶች በቅርቡ ይመጣሉ",
      description: "የማሳወቂያ ምርጫዎች፣ ገጽታ ማበጀት እና የመለያ ደረጃ ቅንጅቶች በቅርቡ እዚህ ይቀርባሉ።",
    },
  },

  // ─── Reports ────────────────────────────────────────────────────────────────
  reports: {
    title: "ሪፖርቶች",
    subtitle: "አጠቃላይ የፍሊት አፈጻጸም እና የሥራ ትንታኔ",
    stats: {
      successRate: "አጠቃላይ ስኬት",
      avgDeliveryTime: "አማካይ የማቅረቢያ ጊዜ",
      onTimePercentage: "በሰዓቱ የመድረስ መጠን",
      fleetUtilization: "የፍሊት አጠቃቀም",
      deliveriesChange: "{pct}% አቅርቦቶች",
      revenueChange: "{pct}% ከቀዳሚው ጋር ሲነጻጸር",
      driversIdle: "{count} ሾፌሮች ስራ የሌላቸው",
      pickupToDelivery: "ጭነት → ማድረስ",
    },
    charts: {
      deliveryVolume: "የዕቃ አቅርቦት መጠን አዝማሚያ",
      statusBreakdown: "የዕቃ አቅርቦት ሁኔታ ዝርዝር",
      vehicleUsage: "የተሽከርካሪ ዓይነት አጠቃቀም",
      total: "ጠቅላላ",
    },
    leaderboard: {
      title: "ከፍተኛ አፈጻጸም ያላቸው ሾፌሮች",
      table: {
        driver: "ሾፌር",
        trips: "ጉዞዎች",
        success: "ስኬት %",
        rating: "ደረጃ",
      },
    },
    vehicles: {
      motorcycles: "ሞተር ብስክሌቶች",
      compactCars: "አነስተኛ መኪናዎች",
      trucksVans: "ጭነት መኪናዎች",
    },
    export: "ሙሉ ሪፖርት አውርድ",
    pdfReport: "PDF ሪፖርት",
    excelReport: "Excel ሪፖርት",
    failedLoad: "ሪፖርቶችን መጫን አልተቻለም",
    failedLoadDesc: "እባክዎ ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።",
  },

  // ─── Forgot Password ────────────────────────────────────────────────────────
  forgotPassword: {
    panelTitle: "የይለፍ ቃልዎን ዳግም ያስጀምሩ",
    panelSubtitle: "ወደ ኢሜልዎ አስተማማኝ ማገናኛ እንልካለን።",
    title: "የይለፍ ቃል ረሳህ?",
    subtitle: "ሊንክ ወደ ኢሜልዎ እናስተላልፋለን",
    description: "ከሒሳብዎ ጋር የተያያዘውን የኢሜይል አድራሻ ያስገቡ፤ የይለፍ ቃል ዳግም ማስጀመሪያ ሊንክ እናስተላልፋለን።",
    emailLabel: "ኢሜይል",
    emailPlaceholder: "you@example.com",
    submit: "ሊንክ ላክ",
    sending: "በመላክ ላይ...",
    backToLogin: "ወደ መግቢያ ተመለስ",
    successTitle: "ኢሜልዎን ያረጋግጡ",
    successBody: "የይለፍ ቃል ዳግም ማስጀመሪያ ሊንክ ወደ {email} ተልኳል። ካላዩ የ spam ፎልደርዎን ይፈትሹ።",
    errorNotFound: "በዚያ ኢሜይል አድራሻ ምንም ሒሳብ አልተገኘም።",
    errorGeneric: "የሆነ ችግር ተፈጥሯል። በኋላ እንደገና ይሞክሩ።",
  },

  // ─── Common ─────────────────────────────────────────────────────────────────
  common: {
    language: "ቋንቋ",
    theme: "ገጽታ",
    darkMode: "ጨለማ ሁናቴ",
    lightMode: "ብርሃን ሁናቴ",
    systemMode: "ስርዓት",
    validation: {
      phoneRequired: "ስልክ ቁጥር ያስፈልጋል",
      phoneFormat: "እባክዎ 09XXXXXXXX ወይም +2519XXXXXXXX ቅርጸት ይጠቀሙ",
      emailRequired: "ኢሜይል ያስፈልጋል",
      emailFormat: "የተሳሳተ የኢሜይል ቅርጸት",
      emailTooLong: "ኢሜይል ከ255 ቁምፊዎች በታች መሆን አለበት",
      urlRequired: "የድረ-ገጽ አድራሻ (URL) ያስፈልጋል",
      urlFormat: "ዩአርኤል በ http:// ወይም https:// መጀመር አለበት",
      urlInvalid: "ልክ ያልሆነ ዩአርኤል (ለምሳሌ፦ https://example.com)",
      passwordRequired: "የይለፍ ቃል ያስፈልጋል",
      passwordTooShort: "ቢያንስ 8 ቁምፊዎች መሆን አለበት",
      passwordUpper: "ቢያንስ አንድ አቢይ (ካፒታል) ፊደል ማካተት አለበት",
      passwordLower: "ቢያንስ አንድ ንዑስ (ስሞል) ፊደል ማካተት አለበት",
      passwordNumber: "ቢያንስ አንድ ቁጥር ማካተት አለበት",
      passwordSpecial: "ቢያንስ አንድ ልዩ ምልክት ማካተት አለበት",
      fieldRequired: "{field} ያስፈልጋል",
      fieldTooLong: "{field} ከ{count} ቁምፊዎች በታች መሆን አለበት",
      plateRequired: "የሰሌዳ ቁጥር ያስፈልጋል",
      plateFormat: "እባክዎ AA-12345 ቅርጸት ይጠቀሙ (2-3 ፊደላት፣ ሰረዝ፣ 5 አሃዞች)",
      passwordsMismatch: "የይለፍ ቃላቱ አይዛመዱም",
    },
  },
};

export default am;
